esphome:
  name: esphome-web-05d6f0
  friendly_name: CO2 Sensor
  min_version: 2025.9.0
  name_add_mac_suffix: false

esp32:
  variant: esp32
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:

# Allow Over-The-Air updates
ota:
- platform: esphome

uart:
  tx_pin: GPIO17
  rx_pin: GPIO16
  baud_rate: 9600

sensor:
  - platform: mhz19
    id: livingroom_mhz19
    co2:
      name: CO2 Value
    temperature:
      name: Temperature
    automatic_baseline_calibration: false

button:
  - platform: template
    name: "Calibrate Zero (20 minutes at 400PPM)"
    id: mhz19_calibrate_zero
    entity_category: diagnostic
    on_press:
      - mhz19.calibrate_zero: livingroom_mhz19

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
