esphome:
  name: esphome-web-fb87ec
  friendly_name: Door Lock
  min_version: 2025.9.0
  name_add_mac_suffix: false

esp32:
  variant: esp32
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:

# Allow Over-The-Air updates
ota:
- platform: esphome

switch:
  - platform: gpio
    name: "Door unlock"
    pin: GPIO18
  - platform: gpio
    name: "Door bell"
    pin: GPIO5

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
