esphome:
  name: esphome-web-4253fc
  friendly_name: ESPHome DSMR
  min_version: 2025.9.0
  name_add_mac_suffix: false

esp32:
  variant: esp32
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:

# Allow Over-The-Air updates
ota:
- platform: esphome

uart:
  id: uart_dsmr
  rx_pin:
    number: GPIO16
    inverted: true
  baud_rate: 115200

dsmr:
  uart_id: uart_dsmr

sensor:
  - platform: dsmr
    energy_delivered_tariff1:
      name: "T1 power consumed"
    energy_delivered_tariff2:
      name: "T2 power consumed"
    energy_returned_tariff1:
      name: "T1 power produced"
    energy_returned_tariff2:
      name: "T2 power produced"
    power_delivered:
      name: "Power consumption"
    power_returned:
      name: "Power production"
    voltage_l1:
      name: "Phase 1 voltage"
    voltage_l2:
      name: "Phase 2 voltage"
    voltage_l3:
      name: "Phase 3 voltage"
    current_l1:
      name: "Phase 1 current"
    current_l2:
      name: "Phase 2 current"
    current_l3:
      name: "Phase 3 current"
    power_delivered_l1:
      name: "Phase 1 consumption"
    power_delivered_l2:
      name: "Phase 2 consumption"
    power_delivered_l3:
      name: "Phase 3 consumption"
    power_returned_l1:
      name: "Phase 1 production"
    power_returned_l2:
      name: "Phase 2 production"
    power_returned_l3:
      name: "Phase 3 production"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
