esphome:
  name: esphome-web-6b7a00
  friendly_name: Living Room Controller
  min_version: 2025.9.0
  name_add_mac_suffix: false

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

esp32:
  board: esp32dev
  variant: esp32
  framework:
    type: esp-idf

network:
  enable_ipv6: true
  min_ipv6_addr_count: 2

# Enable logging
logger:

# Enable Home Assistant API
api:

# Allow Over-The-Air updates
ota:
- platform: esphome

# ============================================================
# Hardware related setup
#
# Setup SPI busses for the display and TFT
# The ESP32-2432S028R uses separate SPI buses for display and touch
spi:
  - id: spi_tft
    clk_pin: GPIO14
    mosi_pin: GPIO13
    miso_pin: GPIO12

# Setup a pin to control the backlight
output:
  - platform: ledc
    pin: GPIO27
    id: backlight_pwm
    inverted: false
  - platform: ledc
    pin: GPIO4
    id: gpio_4
    inverted: true
  - platform: ledc
    pin: GPIO16
    id: gpio_16
    inverted: true
  - platform: ledc
    pin: GPIO17
    id: gpio_17
    inverted: true

# Using a 240 * 320 3,2 inch screen
#
# Setup the ili9xxx platform
#
# Display is used as 240x320 by default so we rotate it to 90°
#
# We print date and time wth the strftime() function, see the ESPHome documentation to
# format date and atime to your locale.
#
display:
 - platform: ili9xxx
   id: esp_display
   color_palette: 8BIT
   model: ili9342
   spi_id: spi_tft
   cs_pin: GPIO15
   dc_pin: GPIO2
   invert_colors: true
   color_order: RGB
   rotation: 180

light:
  - platform: rgb
    id: light_rgb
    name: "RGB LED"
    red: gpio_4
    green: gpio_16
    blue: gpio_17

  - platform: monochromatic
    output: backlight_pwm
    name: Display Backlight
    id: backlight
    restore_mode: ALWAYS_ON

sensor:
  - platform: adc
    id: ambient_light
    pin: GPIO34
    name: "Light detection"
    update_interval: 60s
  - platform: homeassistant
    id: huiskamer_inside_temperature
    entity_id: sensor.huiskamer_inside_temperature
    on_value:
      - lvgl.indicator.update:
          id: temperature_needle
          value: !lambda return x * 10;
      - lvgl.label.update:
          id: temperature_text
          text:
            format: "%.1f°C"
            args: [ 'x' ]


i2c:
  id: i2c_touch
  sda: 33
  scl: 32
  scan: true

# Set up the Goodix GT911 touch platform
# Neglect the interrupt and reset pin.
# GT911 supports a maximum of 4 touch key and guestures
# GT911 provides a standard I2C interface for SCL and SDA to communicate
# It is strongly recommended that transmission rate be kept at or below 400Kbps

touchscreen:
  platform: gt911
  i2c_id: i2c_touch
  display: esp_display
  id: my_touchscreen
  #interrupt_pin: GPIO25
  # update_interval: 50ms
  # address: 0x5D

  transform:
    mirror_x: false
    mirror_y: true
    swap_xy: true

  on_release:
    - if:
        condition: lvgl.is_paused
        then:
          - lvgl.resume
          - lvgl.widget.redraw
          - light.turn_on: backlight

# Create a time sensor, this will fetch time from Home Assistant
time:
  - platform: homeassistant
    id: esptime

# import light status from HA
binary_sensor:
  - platform: homeassistant
    id: main_hall_light
    entity_id: light.main_hall
    trigger_on_initial_state: true
    on_state:
      lvgl.widget.update:
        id: main_hall_button
        state:
          checked: !lambda return x;

font:
  - file: "fonts/materialdesignicons-webfont.ttf"
    id: material_icons_20
    size: 20
    bpp: 4
    glyphs: [
      "\U000F0F54", # mdi:home-thermometer
      "\U000F0590", # mdi:weather-cloudy
      "\U000F1901", # mdi:home-battery
    ]

lvgl:
  displays:
    - esp_display
  on_idle:
    - timeout: 30s
      then:
        - light.turn_off: backlight
        - lvgl.pause:
  theme:
    button:
      bg_color: 0x2F8CD8
      bg_grad_color: 0x005782
      bg_grad_dir: VER
      bg_opa: COVER
      border_color: 0x0077b3
      border_width: 1
      text_color: 0xFFFFFF
      pressed: # set some button colors to be different in pressed state
        bg_color: 0x006699
        bg_grad_color: 0x00334d
      checked: # set some button colors to be different in checked state
        bg_color: 0x1d5f96
        bg_grad_color: 0x03324A
        text_color: 0xfff300
  style_definitions:
    - id: page_selector
      bg_color: 0x2f8cd8
      bg_grad_color: 0x005782
      bg_grad_dir: HOR
      bg_opa: COVER
      border_opa: TRANSP
      radius: 0
      pad_all: 0
      pad_row: 0
      pad_column: 0
      border_color: 0x0077b3
      text_color: 0xffffff
      text_font: material_icons_20
      width: 30
      height: 100%
  top_layer:
    widgets:
      - buttonmatrix:
          align: TOP_LEFT
          styles: page_selector
          pad_all: 0
          outline_width: 0
          id: top_layer
          items:
            styles: page_selector
          rows:
            - buttons:
                - id: climate_control_select_page
                  text: "\U000F0F54"
                  on_press:
                    then:
                      lvgl.page.show: climate_control_page
            - buttons:
                - id: weather_select_page
                  text: "\U000F0590"
                  on_press:
                    then:
                      lvgl.page.show: weather_page
            - buttons:
                - id: battery_select_page
                  text: "\U000F1901"
                  on_press:
                    then:
                      lvgl.page.show: battery_page
  pages:
    - id: climate_control_page
      widgets:
        - meter:
            align: CENTER
            height: 180
            width: 180
            scales:
              - range_from: 0 # scale for the needle value
                range_to: 400
                angle_range: 240
                rotation: 150
                indicators:
                  - line:
                      id: temperature_needle
                      width: 2
                      color: 0xFF0000
                      r_mod: -4
                  - tick_style:
                      start_value: -10
                      end_value: 40
                      color_start: 0x0000bd
                      color_end: 0xbd0000
                      width: 1
              - range_from: 0 # scale for the value labels
                range_to: 40
                angle_range: 240
                rotation: 150
                ticks:
                  width: 1
                  count: 51
                  length: 10
                  color: 0x000000
                  major:
                    stride: 5
                    width: 2
                    length: 10
                    color: 0x404040
                    label_gap: 10
            widgets:
              - label:
                  id: temperature_text
                  text: "-.-°C"
                  align: CENTER
                  y: 45
              - label:
                  text: "Indoor"
                  align: CENTER
                  y: 65
    - id: weather_page
      widgets:
        - button:
            id: main_hall_button
            align: CENTER
            width: 100
            height: 70
            checkable: true
            widgets:
              - label:
                  align: CENTER
                  text: 'Main Hall'
            on_click:
              - homeassistant.action:
                  action: light.toggle
                  data:
                    entity_id: light.main_hall
    - id: battery_page
